import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/Header"
import TopCards from '../components/TopCards'
import Barchart from '../components/Barchart'
import RecentOrders from '../components/RecentOrders'
import clientPromise from '../lib/mongodb'
import { getSession,useSession } from "next-auth/react";
import dbConnect from "../lib/dbConnect";

  
export async function getServerSideProps(context) {


  try {
    await dbConnect();
    const client = await clientPromise;
    const db = client.db(process.env.MONGODB_DATABASE);
    

    const ctx = await getSession(context);
    // `await clientPromise` will use the default database passed in the MONGODB_URI
    // However you can use another database (e.g. myDatabase) by replacing the `await clientPromise` with the following code:
    //
    // `const client = await clientPromise`
    // `const db = client.db("myDatabase")`
    //
    // Then you can execute queries against your database like so:
    // db.find({}) or any of the MongoDB Node Driver commands

    return {
      props: { isConnected: true, session: ctx },
    };
  } catch (e) {
    console.error(e);
    return {
      props: { isConnected: false },
    };
  }


}
  


export default function Home({
  isConnected
}) 
{
  const {data:session} = useSession()
  console.log(session)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-green-50 min-h-screen">
        <Header/>
        <TopCards/>
        <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4'>
          <Barchart/>
          <RecentOrders/>
        </div>
      </main>
    </>
  )
}
